// <auto-generated />
using System;
using FusePortal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FusePortal.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260122150046_initiala")]
    partial class initiala
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.ExamAggregate.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Answers")
                        .HasColumnType("TEXT");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Results")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScoreFrom100")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.SubjectAggregate.Lecturer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Lecturer");
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.SubjectAggregate.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.SubjectAggregate.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.SubjectAggregate.Syllabus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Syllabus");
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.UniversityAggregate.University", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Convo.ChatAggregate.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResponseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Convo.ChatAggregate.Message", b =>
                {
                    b.Property<int>("CountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FromUser")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CountNumber");

                    b.HasIndex("ChatId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Convo.ChatAggregate.MessageFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageCountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageCountNumber");

                    b.HasIndex("MessageId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Identity.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UniversityUser", b =>
                {
                    b.Property<Guid>("StudentsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniversitiesId")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentsId", "UniversitiesId");

                    b.HasIndex("UniversitiesId");

                    b.ToTable("UniversityUser");
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.ExamAggregate.Exam", b =>
                {
                    b.HasOne("FusePortal.Domain.Entities.Academic.SubjectAggregate.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.SubjectAggregate.Lecturer", b =>
                {
                    b.HasOne("FusePortal.Domain.Entities.Academic.SubjectAggregate.Subject", null)
                        .WithMany("Lecturers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.SubjectAggregate.Schedule", b =>
                {
                    b.HasOne("FusePortal.Domain.Entities.Academic.SubjectAggregate.Subject", null)
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FusePortal.Domain.Common.ValueObjects.LectureDate.LectureDate", "LectureDate", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("End")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("TEXT");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("Schedule");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.Navigation("LectureDate")
                        .IsRequired();
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.SubjectAggregate.Subject", b =>
                {
                    b.HasOne("FusePortal.Domain.Entities.Identity.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.SubjectAggregate.Syllabus", b =>
                {
                    b.HasOne("FusePortal.Domain.Entities.Academic.SubjectAggregate.Subject", null)
                        .WithMany("Syllabuses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.UniversityAggregate.University", b =>
                {
                    b.OwnsOne("FusePortal.Domain.Common.ValueObjects.Address.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UniversityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("UniversityId");

                            b1.ToTable("Universities");

                            b1.WithOwner()
                                .HasForeignKey("UniversityId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Convo.ChatAggregate.Chat", b =>
                {
                    b.HasOne("FusePortal.Domain.Entities.Identity.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Convo.ChatAggregate.Message", b =>
                {
                    b.HasOne("FusePortal.Domain.Entities.Convo.ChatAggregate.Chat", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Convo.ChatAggregate.MessageFile", b =>
                {
                    b.HasOne("FusePortal.Domain.Entities.Convo.ChatAggregate.Message", null)
                        .WithMany("Files")
                        .HasForeignKey("MessageCountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FusePortal.Domain.Entities.Convo.ChatAggregate.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Identity.UserAggregate.User", b =>
                {
                    b.OwnsOne("FusePortal.Domain.Common.ValueObjects.Address.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityUser", b =>
                {
                    b.HasOne("FusePortal.Domain.Entities.Identity.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FusePortal.Domain.Entities.Academic.UniversityAggregate.University", null)
                        .WithMany()
                        .HasForeignKey("UniversitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Academic.SubjectAggregate.Subject", b =>
                {
                    b.Navigation("Lecturers");

                    b.Navigation("Schedules");

                    b.Navigation("Syllabuses");
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Convo.ChatAggregate.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("FusePortal.Domain.Entities.Convo.ChatAggregate.Message", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
